[tool.poetry]
name = "fastapi-mproc"
version = "0.1.0"
description = ""
authors = ["Majoson <majoson@qq.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
